apiVersion: v1
kind: Service
metadata:
  labels:
    app: keda-demo
  name: keda-demo
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: keda-demo
